### ISSUE TITLE
start script failing

### ISSUE THREAD

**Issue by kallolborah** [atpar/example#3]
Hi, when I run yarn start:env, I get this error. Does this example require any other configuration prior to running the script ?

```
yarn run v1.22.10
$ ./scripts/start-env.sh
Starting new ganache-cli instance with an ap-chain snapshot.
Applying Pre-signed Transactions...
/mnt/d/code/example/node_modules/web3-core-helpers/src/errors.js:42
        return new Error(message);
               ^

Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/mnt/d/code/example/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/mnt/d/code/example/node_modules/web3-providers-http/src/index.js:98:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/mnt/d/code/example/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/mnt/d/code/example/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/mnt/d/code/example/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/mnt/d/code/example/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at ClientRequest.emit (node:events:369:20)
    at Socket.socketOnEnd (node:_http_client:496:9)
    at Socket.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
error Command failed with exit code 1.
```

**Comment by kallolborah** [comment]
I could run yarn asset:create and asset:tokenize in this example project without running start:env script by first running the setup-ap-chain script in the ap-monorepo. 

When I run start:env after deploying the contracts with setup-ap-chain, I get a different error 
```
$ ./scripts/start-env.sh
Starting new ganache-cli instance with an ap-chain snapshot.
Applying Pre-signed Transactions...
/mnt/d/code/example/node_modules/web3-core-helpers/src/errors.js:29
        return new Error('Returned error: ' + message);
               ^

Error: Returned error: the tx doesn't have the correct nonce. account has nonce of: 45 tx has nonce of: 38
    at Object.ErrorResponse (/mnt/d/code/example/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /mnt/d/code/example/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/mnt/d/code/example/node_modules/web3-providers-http/src/index.js:102:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/mnt/d/code/example/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/mnt/d/code/example/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/mnt/d/code/example/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/mnt/d/code/example/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
error Command failed with exit code 1.
```

I am not sure what is wrong ? Or am I making a mistake somewhere ?
